# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketgapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes: 
  mongo_data:
